"""
session_html_render.py —— 时间线 HTML 的片段渲染

- _extract_tool_calls       提取【调用:...】标记
- _render_timeline_head     渲染 <head> + <header>
- _render_timeline_messages 渲染消息循环
- _render_timeline_footer   渲染 <footer>
"""
from __future__ import annotations

import re
from typing import Any, Dict, List

from fr_cli.weapon.session_html_md import _escape, _render_content
from fr_cli.weapon.session_html_styles import (
    ROLE_ICONS,
    ROLE_LABELS,
    _TIMELINE_CSS,
)


def _extract_tool_calls(text: str) -> List[Dict[str, str]]:
    """提取【调用:tool_name({...})】标记"""
    calls = []
    for m in re.finditer(r"【调用：(\w+)\((.*?)\)】", text, re.DOTALL):
        calls.append({
            "tool": m.group(1),
            "args": m.group(2)[:200] + ("..." if len(m.group(2)) > 200 else ""),
        })
    return calls


def _render_timeline_head(
    title: str, session_filename: str, now: str,
    total: int, user_count: int, ai_count: int,
) -> str:
    """渲染 HTML 头部 + 内嵌 CSS + <header>"""
    return f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{_escape(title)}</title>
<style>{_TIMELINE_CSS}</style>
</head>
<body>
<header>
  <h1>📜 {_escape(title)}</h1>
  <div style="color: var(--text-secondary); font-size: 13px;">
    {_escape(session_filename) if session_filename else ""}
  </div>
  <div class="stats">
    <span><span class="dot user"></span> 用户: {user_count}</span>
    <span><span class="dot ai"></span> AI: {ai_count}</span>
    <span>总计: {total} 条</span>
    <span>生成于: {_escape(now)}</span>
  </div>
</header>
<div class="timeline">
"""


def _render_timeline_messages(messages: List[Dict[str, Any]]) -> str:
    """渲染消息循环(每条消息一行 + 工具调用折叠)"""
    parts = []
    for msg in messages:
        role = msg.get("role", "user")
        content = msg.get("content", "")
        tool_calls = _extract_tool_calls(content) if role == "assistant" else []

        icon = ROLE_ICONS.get(role, "?")
        label = ROLE_LABELS.get(role, role)

        parts.append(f'<div class="message {role}">\n')
        parts.append(f'  <div class="role">{icon} {label}</div>\n')
        parts.append('  <div class="content">\n')
        parts.append(f'    {_render_content(content)}\n')
        parts.append('  </div>\n')

        if tool_calls:
            parts.append('  <div class="tool-calls">\n')
            parts.append('    <strong>🔧 工具调用</strong>\n')
            for tc in tool_calls:
                parts.append(
                    f'    <div class="tool-call">\n'
                    f'      <span class="name">{_escape(tc["tool"])}</span>\n'
                    f'      <details><summary>参数</summary>\n'
                    f'        <div class="args">{_escape(tc["args"])}</div>\n'
                    f'      </details>\n'
                    f'    </div>\n'
                )
            parts.append('  </div>\n')

        parts.append('</div>\n')
    return "".join(parts)


def _render_timeline_footer(now: str) -> str:
    """渲染 <footer>"""
    return f"""</div>
<footer>
  Generated by fr-cli • {_escape(now)}
</footer>
</body>
</html>"""
