"""
conf 包入口
首次导入时自动触发路径迁移
"""
from fr_cli.conf.paths import (
    migrate, ROOT,
    CONFIG_FILE, CONFIG_BACKUP, CONTEXT_FILE, MODELS_YAML,
    SESSIONS_DIR, SESSIONS_MANUAL_DIR, SESSIONS_AUTO_DIR,
    PLUGIN_DIR, AGENTS_DIR, MASTER_DIR,
    REMOTE_DIR, REMOTE_AGENTS_FILE, REMOTE_HOSTS_FILE,
    DATABASE_FILE, GATEWAY_FILE, PERSONALITIES_FILE, SKILLS_DIR,
    IMAGE_CONFIG_FILE, REGISTRY_FILE, CONTEXT_FILES_FILE,
    MCP_DIR, MCP_SERVERS_FILE,
    DAEMON_DIR, DAEMON_CONFIG_FILE, DAEMON_PID_FILE, DAEMON_STOP_FILE,
    DAEMON_TOKEN_FILE, DAEMON_HERMES_CONFIG_FILE,
    RAG_DIR, RAG_DB_DIR, RAG_WATCHER_PID_FILE, RAG_WATCHER_STOP_FILE, RAG_WATCHER_LOG_FILE,
)

# 触发迁移（幂等）
migrate()

__all__ = [
    "migrate", "ROOT",
    "CONFIG_FILE", "CONFIG_BACKUP", "CONTEXT_FILE", "MODELS_YAML",
    "SESSIONS_DIR", "SESSIONS_MANUAL_DIR", "SESSIONS_AUTO_DIR",
    "PLUGIN_DIR", "AGENTS_DIR", "MASTER_DIR",
    "REMOTE_DIR", "REMOTE_AGENTS_FILE", "REMOTE_HOSTS_FILE",
    "DATABASE_FILE", "GATEWAY_FILE", "PERSONALITIES_FILE", "SKILLS_DIR",
    "IMAGE_CONFIG_FILE", "REGISTRY_FILE", "CONTEXT_FILES_FILE",
    "MCP_DIR", "MCP_SERVERS_FILE",
    "DAEMON_DIR", "DAEMON_CONFIG_FILE", "DAEMON_PID_FILE", "DAEMON_STOP_FILE",
    "DAEMON_TOKEN_FILE", "DAEMON_HERMES_CONFIG_FILE",
    "RAG_DIR", "RAG_DB_DIR", "RAG_WATCHER_PID_FILE", "RAG_WATCHER_STOP_FILE", "RAG_WATCHER_LOG_FILE",
]
